### probar rutas del usuarios
### optener usuario metodo get
GET http://localhost:3000/usuario

### crear usuario metodo post
POST http://localhost:3000/usuario

### editar usuario metodo put
PUT http://localhost:3000/usuario

### eliminar usuario metodo delete
DELETE http://localhost:3000/usuario

###autenticar probar ruta
POST http://localhost:3000/autenticar

### verificarToken probar ruta
POST http://localhost:3000/verificarToken

Content-Type: application/json
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDA5MzY0NjZ9.89D8eWquqEzGcljwuW1pIedlL9H5sImLhAeWbV1uGjE"
}

### para probar ruta envio de Email
POST http://localhost:3000/subirArchivo

###optener datos con axios
GET http://localhost:3000/optenerProvincias